customhost = "employeedb.cmjfs9whhlss.us-east-1.rds.amazonaws.com"
customuser = "pandey"
custompass = "tereliye"
customdb = "employee"
custombucket = "addemployees-saksham"
customregion = "us-east-1"
